#!/usr/bin/perl
#initalize list(array)
@x = (1,2,3);
@y = (4,5,6);
#Create the new array and index
@z;
$i =0;
while($i<3)
{
	#add the elements from x and y at i and put then in z
	push @z, @x[$i]+@y[$i];
	$i = $i+1; #increment the counter (i++)
}
#Print the array
print "@z\n";
