#!/bin/bash
min=-23
max=31
declare -a randArray 
maxNum=-24
maxCount=0
curNum=0
curCount=0
posNum=0
negNum=0
maxNum=0
minNum=0
avg=0
sumNum=0
sumOfSq=0
function getAvg()
{
	avg=$[sumNum/50]
}

function getMode()
{
	count=-23	
	while [ "$count" -le 31 ]
	do
		maxCount=0
		curNum=$count
		curCount=0
		for i in ${randArray[@]} 
		do 
			if [ "$i" -eq "$maxNum" ]
			then
			maxCount=$[maxCount+1]
			fi

			if [ "$i" -eq "$curNum" ]
			then
			curCount=$[curCount+1]
			fi


		done

		if [ "$curCount" -ge "$maxCount" ]
		then
		maxNum=$curNum
		maxCount=$curCount
		fi
		count=$[count+1]
	done

	echo "---Occured the most $maxNum"
}

function sumOfSquares()
{
	#Outprints the array
	for i in ${randArray[@]} 
	do 
		temp=$[i*i]
		sumOfSq=$[sumOfSq+temp]
	done
	echo "Sum of sqaures$sumOfSq"
}

count=1


while [ "$count" -le 50 ]
do
	rand=$[RANDOM%(max-min+1)+min]
	randArray[$count]=$rand
	if [ "$rand" -le -1 ]
	then
		posNum=$[posNum+1]
	else
		negNum=$[negNum+1]
	fi
	
	if [ "$rand" -ge "$maxNum" ]
	then
		maxNum=$rand
	fi

	if [ "$rand" -le "$minNum" ]
	then
		minNum=$rand
	fi

	echo "$rand" 
	sumNum=$[sumNum+rand]
	count=$[count+1]
done
 
function print()
{
	getAvg
	getMode
	sumOfSquares
	echo "Avg = $avg Mode $maxNum Sum = $sumOfSq"
}



#Outprints the array
#for i in ${randArray[@]} 
#do 
	#echo $i; 
#done

echo "Number of P $posNum  and N: $negNum"
echo "max num is $maxNum min num is $minNum"
echo $sumNum
#avg=$[sumNum/100]

echo $avg


echo "Max = $maxNum" >> "repotsbash.txt"
echo "Min = $minNum" >> "repotsbash.txt"
echo "Postive = $posNum" >> "repotsbash.txt"
echo "Negative = $negNum" >> "repotsbash.txt"
echo "avg = $avg" >> "repotsbash.txt"
echo "------------------------------" >> "repotsbash.txt"

print


